import { useEffect, useRef, useState } from 'react';
import { MapPin, Clock, Ticket, ArrowUpRight } from 'lucide-react';
import { ACTIVITIES_PICKS, gygHref, GYG_PRICE_AS_OF } from '../shared/gyg/picks';
import { pickIcon } from '../lib/pickIcon';
import { useLang } from '../i18n/useLang';
import type { Lang } from '../i18n/useLang';

/** GetYourGuiden oma kielikoodi. Eri muoto kuin polun etuliite (`/fi-fi/`). */
const GYG_LOCALE: Record<Lang, string> = {
  en: 'en-GB', fi: 'fi-FI', de: 'de-DE', ja: 'ja-JP', es: 'es-ES',
  'pt-BR': 'pt-BR', 'zh-CN': 'zh-CN', ko: 'ko-KR', fr: 'fr-FR',
  it: 'it-IT', nl: 'nl-NL', sv: 'sv-SE',
};

/**
 * Tuotetunnukset samoista poiminnoista, jotka kortitkin nayttavat: polun hanta
 * `…-t300556` on GetYourGuiden tuotetunnus.
 *
 * 🔴 Tunnukset luetaan poimintalistasta, ei kirjoiteta tahan kasin. Kasin
 * yllapidetty rinnakkainen lista erkaantuisi ensimmaisessa muutoksessa, ja
 * widget nayttaisi eri tuotteet kuin varakortit saman otsikon alla.
 */
const TOUR_IDS = ACTIVITIES_PICKS.map((r) => (r.path.match(/-t(\d+)$/) || [])[1])
  .filter(Boolean)
  .join(',');

/**
 * Direct GetYourGuide product deep links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * The WHOLE card is the link. Every path in shared/gyg/picks.ts was opened in
 * a real browser before shipping; a wrong or delisted GetYourGuide id does not
 * 404, it redirects to a city listing with HTTP 200.
 *
 * Price IS rendered, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenoti ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked winter activities, bookable online through GetYourGuide.",
    "fi": "Poimitut talviaktiviteetit, varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte Winteraktivitäten, online über GetYourGuide buchbar.",
    "ja": "厳選した冬のアクティビティ。GetYourGuide でオンライン予約できます。",
    "es": "Actividades de invierno seleccionadas, reservables en línea con GetYourGuide.",
    "pt-BR": "Atividades de inverno selecionadas, reserváveis online via GetYourGuide.",
    "zh-CN": "精选冬季活动，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 겨울 액티비티, GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection d'activités hivernales, réservables en ligne via GetYourGuide.",
    "it": "Attività invernali selezionate, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde winteractiviteiten, online te boeken via GetYourGuide.",
    "sv": "Utvalda vinteraktiviteter, bokas online via GetYourGuide."
  },
  "headingCategory": {
    "en": "Browse and book on GetYourGuide",
    "fi": "Selaa ja varaa GetYourGuidessa",
    "de": "Auf GetYourGuide stöbern und buchen",
    "ja": "GetYourGuide で探して予約",
    "es": "Explora y reserva en GetYourGuide",
    "pt-BR": "Explore e reserve no GetYourGuide",
    "zh-CN": "在 GetYourGuide 浏览并预订",
    "ko": "GetYourGuide에서 둘러보고 예약",
    "fr": "Parcourez et réservez sur GetYourGuide",
    "it": "Sfogli e prenoti su GetYourGuide",
    "nl": "Bekijk en boek op GetYourGuide",
    "sv": "Bläddra och boka på GetYourGuide"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current, we do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen; emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

/**
 * The as-of date next to each price, in the page's locale. Not "today" —
 * the day the price was actually read off GetYourGuide, which is the only date
 * we can stand behind.
 */
const fiDate = (iso: string, locale: string): string => {
  const d = new Date(iso + 'T00:00:00Z');
  // timeZone UTC because the stamp is a plain date: without it a reader west of
  // UTC is shown the previous day. Locale is the page's, never the browser's.
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString(locale, { day: 'numeric', month: 'numeric', year: 'numeric', timeZone: 'UTC' });
};

export default function GygPicks() {
  const lang = useLang();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  const rows = ACTIVITIES_PICKS;

  /**
   * Latautuiko GetYourGuiden widget? Jos ei, kavija ei ole antanut
   * evastesuostumusta kolmannen osapuolen upotuksille, ja omat kortit
   * naytetaan sen sijaan. Ilman tata osio olisi silloin tyhja.
   */
  const boxRef = useRef<HTMLDivElement>(null);
  const [blocked, setBlocked] = useState(false);

  useEffect(() => {
    let cancelled = false;
    let waited = 0;
    const FIRST = 2500, STEP = 1000, MAX = 12000;
    const tick = (delay: number): ReturnType<typeof setTimeout> =>
      setTimeout(() => {
        if (cancelled) return;
        waited += delay;
        if (boxRef.current?.querySelector('iframe')) { setBlocked(false); return; }
        setBlocked(true);
        if (waited < MAX) tick(STEP);
      }, delay);
    const timer = tick(FIRST);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [lang]);

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-[#0F172A]">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#22D3EE]">{t(L.kicker)}</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 text-[#F9FAFB]">
            {t(L.headingProduct)}
          </h2>
          <p className="max-w-2xl text-white/70">{t(L.ledeProduct)}</p>
        </div>

        {/* Jarjestajien omat tuotekuvat, arvosanat ja TAMAN PAIVAN hinnat.
            `key` kielella: kielenvaihto uudelleenrakentaa widgetin. */}
        <div
          ref={boxRef}
          key={`gyg-${lang}`}
          className={blocked ? 'h-0 overflow-hidden' : 'min-h-[320px]'}
          data-gyg-widget="activities"
          data-gyg-partner-id="VRMKD7N"
          data-gyg-locale-code={GYG_LOCALE[lang]}
          data-gyg-cmp="lv_laplandactivities_home"
          data-gyg-tour-ids={TOUR_IDS}
          data-gyg-number-of-items="4"
        />

        {/* Varapolku: nayttaa vain jos widget ei latautunut. Hinta on talloin
            katalogin hinta paivayksineen, ei tamanpaivainen. */}
        <div className={blocked ? 'grid gap-5 sm:grid-cols-2 lg:grid-cols-4' : 'hidden'}>
        {rows.map((p) => (
          <a
            key={p.path}
            href={gygHref(p, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-col overflow-hidden rounded-2xl border bg-white/5 border-white/10 no-underline transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:border-[#22D3EE]/50"
          >
            {/* 🔴 Ei kuvaa: tuotekortti on lupaus yhdestä nimetystä tuotteesta, joten
                yleiskuva samasta lajista (§24) ja tekoälykuva ovat molemmat poissuljettuja,
                ja GetYourGuiden oma kuva kuuluu järjestäjälle. Ikoni + typografia kantavat
                kortin, sama ratkaisu kuin kohdesivujen DestinationPicks-karusellissa.
                Poistetut AI-kuvat: ks. src/data/gygImages.ts. */}
            {(() => { const Icon = pickIcon(p.title); return (
              <span className="mx-5 mt-5 inline-flex w-11 h-11 shrink-0 rounded-xl bg-[#DB2777]/15 items-center justify-center">
                <Icon className="h-5 w-5 text-[#F472B6]" aria-hidden="true" />
              </span>
            ); })()}

            <div className="flex flex-1 flex-col p-5">
              <p className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#22D3EE]">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" />
                {p.place}
              </p>

              {/* 🔴 This renders in Bebas Neue: the site's global rule sets the face
                  for every h1..h6, so `text-base font-bold` gave the card's most
                  important line — what you are actually buying — a 16px condensed
                  display face at synthetic weight 700. Bebas ships one weight, so
                  700 is browser-synthesised and smears the letterforms; measured
                  live, the x-height came out smaller than the 11px legal line below
                  it. Sized to match the site's other Bebas card titles and the fake
                  bold dropped. */}
              <h3 className="mt-2 flex-1 text-lg sm:text-xl tracking-wide leading-tight text-[#F9FAFB]">{p.title}</h3>

              {/* Only when a real length exists — one source row carried a sales
                  badge in this field, and a badge is not a duration. */}
              {p.duration && (
                <p className="mt-2 inline-flex items-center gap-1.5 text-sm text-white/60">
                  <Clock className="h-3.5 w-3.5" aria-hidden="true" />
                  {p.duration}
                </p>
              )}

              {/* GetYourGuide's OWN "from" price, with source and date beside it.
                  It is not our price and we cannot keep it current — the partner
                  changes it. Rendering it bare would be a promise we break on
                  their behalf; rendering it dated is a fact about a moment.
                  Deliberately no "per person": spot checks showed per-person on
                  the rows we opened, but the catalogue does not record the unit
                  and some GetYourGuide products are priced per group. */}
              {p.price && (
                <p className="mt-3 flex items-baseline gap-1.5">
                  <span className="text-[11px] uppercase tracking-wider text-white/60">{t(L.priceFrom)}</span>
                  <span className="text-lg font-bold text-[#F9FAFB]">{p.price}</span>
                </p>
              )}

              <span className="mt-4 inline-flex items-center justify-center gap-2 rounded-full bg-[#DB2777] px-4 py-2.5 text-sm font-bold text-white transition-opacity group-hover:opacity-90">
                <Ticket className="h-4 w-4" aria-hidden="true" />
                {t(L.ctaProduct)}
                <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
              </span>

              {/* Per-rivin priceAsOf voittaa katalogin päiväyksen: rivin hinta on
                  voitu lukea eri päivänä kuin katalogiajo (ks. picks.ts). */}
              <span className="mt-2 text-center text-[11px] text-white/60">
                {p.price ? `${t(L.priceSource)} ${fiDate(p.priceAsOf ?? GYG_PRICE_AS_OF, lang)}` : t(L.via)}
              </span>
            </div>
          </a>
        ))}
        </div>
      </div>
    </section>
  );
}
