// Generated by scripts/gyg-wire-images.mjs — do not edit by hand.
//
// Card images for the GetYourGuide picks, keyed by the product path so a card
// and its image can never drift apart. AI-generated with Picsart (gpt-image-2)
// on 2026-07-30; GetYourGuide's own photos are NOT used, they belong to the
// operators. One image is used on exactly one ecosystem site.
import img0 from '../assets/gyg/reindeer-experience-with-sleigh-ride.webp';
import img1 from '../assets/gyg/husky-reindeer-experience-with-snowmobile-ride.webp';
import img2 from '../assets/gyg/northern-lights-tour-with-guaranteed-sightings.webp';
import img3 from '../assets/gyg/yllasjarvi-ice-floating-experience.webp';

export const GYG_IMAGES: Record<string, string> = {
  'rovaniemi-l2653/rovaniemi-reindeer-experience-with-sleigh-ride-t300556': img0,
  'rovaniemi-l2653/rovaniemi-husky-reindeer-experience-with-snowmobile-ride-t320613': img1,
  // northern-lights-tour-with-guaranteed-sightings.webp: no PNG in _gyg-images — generated straight into this repo
  'kittila-l165074/levi-northern-lights-tour-with-guaranteed-sightings-t693623': img2,
  // yllasjarvi-ice-floating-experience.webp: no PNG in _gyg-images — generated straight into this repo
  'akaslompolo-l2931/ice-floating-experience-yllas-t97086': img3,
};
