// All imagery is locally hosted in /public/images/. WebP optimized via
// scripts/optimize-images.mjs. No Google Drive, no Unsplash, no third-party CDN.
//
// CURATED HIGH-RES POOL (12 images, brand-clean, all WebP, generated by Vesa):
//   /heroes/slider-01-husky-aurora.webp        (husky team + aurora)
//   /heroes/slider-02-snowmobile-fells.webp    (snowmobile + fjells)
//   /heroes/slider-03-summer-hike.webp         (summer hike, midnight sun)
//   /heroes/slider-04-glass-igloo.webp         (glass igloo, twilight)
//   /heroes/slider-05-reindeer-lavvu.webp      (reindeer + Sámi lavvu)
//   /categories/summer.webp                    (summer landscape, vertical-friendly)
//   /hotels/glass-igloo-aurora.webp            (single igloo + aurora)
//   /hotels/log-cabin-lakeside.webp            (red log cabin, lakeside)
//   /hotels/fell-resort-levi.webp              (alpine ski resort)
//   /hotels/boutique-hotel-rovaniemi.webp      (modern hotel exterior)
//   /hotels/smoke-sauna-cabin-saariselka.webp  (savusauna cabin)
//   /og/og-default.webp                        (wide aurora composition for OG)

const local = (file: string) => `/images/${file}`;

// === SAFE / CONFIRMED-CLEAN HIGH-RES POOL ===
// 🔴🔴 2026-08-23: tama lohko VAITTI ennen etta "every alias maps to a UNIQUE
// entry ... guarantees no two surfaces share the same image at the same time".
// Se ei pitanyt paikkaansa, ja juuri se vakuutus piilotti ongelman. Mitattuna
// renderoidylta etusivulta: slider-03 x3, slider-05 x3, fell-resort-levi x3,
// og-default x3, ja viisi muuta x2. Aliaksia on enemman kuin kuvia, joten osa
// niista OSOITTAA VALTTAMATTA samaan tiedostoon.
//
// 🔴 og/og-default.webp on sosiaalisen jaon kuva. Se oli kortin kuvana
// yhdeksassa eri lupauksessa (revontulet x2, Sampo-jaanmurtaja, pilkkiminen,
// lapset lumessa, jainen jarvi, Inari talvella, Posio kesalla). Nyt jokaisella
// on oma kuva. ALA koskaan laita og-defaultia takaisin sisaltokuvaksi - se on
// merkki siita etta kuva puuttuu, ei kuva.
//
// Oikea sanamuoto: alla oleva allas on brandipuhdas ja paikallinen, mutta se ei
// riita kattamaan kaikkia pintoja. Jos tarvitset uuden kortin, TEE UUSI KUVA.

export const HERO = {
  // Primary aurora — used in newsletter popup decoration etc.
  aurora:           local('heroes/slider-01-husky-aurora.webp'),

  // Used by destinations.ts / categories.ts via legacy alias names
  auroraLake:       local('activities/northern-lights/aurora-lake.webp'), // aurora + jaatynyt jarvi
  snowyForest:      local('heroes/slider-02-snowmobile-fells.webp'), // wide forest+sled
  huskyAurora:      local('heroes/slider-01-husky-aurora.webp'),
  huskySnowmobile:  local('heroes/slider-02-snowmobile-fells.webp'),
  campfire:         local('hotels/log-cabin-lakeside.webp'),         // cabin + outdoor
  glassIgloo:       local('hotels/glass-igloo-aurora.webp'),

  // Legacy alias names (used by destinations.ts) — all now map to high-res WebPs
  santaClaus:       local('heroes/slider-05-reindeer-lavvu.webp'),
  reindeerHerd:     local('heroes/slider-05-reindeer-lavvu.webp'),
  huskyTeam:        local('heroes/slider-01-husky-aurora.webp'),
  kidsSnow:         local('activities/winter/kids-snow-play.webp'),
  cabin:            local('hotels/log-cabin-lakeside.webp'),
  iceLake:          local('heroes/inari-winter-lake.webp'),
  fells:            local('hotels/fell-resort-levi.webp'),
  midnightSun:      local('heroes/slider-03-summer-hike.webp'),
  smokesauna:       local('hotels/smoke-sauna-cabin-saariselka.webp'),
  fjell:            local('heroes/slider-02-snowmobile-fells.webp'),
  village:          local('hotels/boutique-hotel-rovaniemi.webp'),

  // Animal-experience card variety — derived from existing in-repo Drive imagery
  // (hero_01 / mkt_04), downscaled to WebP+AVIF. Feeds the reindeer/husky rotation
  // so sibling cards no longer repeat the same single image.
  reindeerSunset:   local('heroes/reindeer-herd-sunset.webp'),  // reindeer herd, golden sunset
  huskyDay:         local('heroes/husky-sled-day.webp'),        // daytime husky-sled team
  skiResortWinter:  local('heroes/ski-resort-winter.webp'),     // snowy fell ski slope at dusk
  ruskaRidge:       local('heroes/slider-03-summer-hike.webp'), // autumn ruska fell ridge + hikers
  salmonFishing:    local('activities/summer/salmon-fishing.webp'), // river salmon fishing, used by fishing category hero

  // 2026-07-24 new destination heroes (Picsart gemini-3-pro-image 2K, unique to this site).
  // kemijarvi file is named for an easy swap: Vesa has real Kemijärvi photos to drop in later.
  pyhaLuosto:       local('heroes/pyha-luosto-fells.webp'),     // twin fells + national park, winter dusk
  kemijarvi:        local('heroes/kemijarvi-lake-town.webp'),   // lake + rail + small-town winter vibe
} as const;

// HERO_BRANDED — kept as alias for legacy data references
export const HERO_BRANDED = {
  magicOfLapland:  HERO.glassIgloo,
  gatewayLapland:  HERO.village,
  discoverLapland: HERO.huskySnowmobile,
  tasteArctic:     HERO.smokesauna,
  distinctive:     HERO.huskyAurora,
  homeArctic:      HERO.cabin,
  relaxRecharge:   HERO.smokesauna,
} as const;

// MKT pool — used by categories.ts. Each key maps to a UNIQUE high-res file.
export const MKT = {
  huskyAuroraFamily: HERO.huskyAurora,            // slider-01
  huskySnowmobile:   HERO.huskySnowmobile,        // slider-02
  huskyAurora:       HERO.huskyAurora,            // slider-01
  huskyDaylight:     HERO.huskySnowmobile,        // slider-02
  campfireNight:     HERO.cabin,                  // log-cabin-lakeside
  campfireClose:     HERO.cabin,
  campfireTripod:    HERO.cabin,
  campfireStars:     HERO.cabin,
  igluCouple:        HERO.glassIgloo,             // hotels/glass-igloo-aurora
  igluAurora:        HERO.glassIgloo,
  igluClose:         HERO.glassIgloo,
  igluDramatic:      HERO.glassIgloo,
  reindeerSled:      HERO.santaClaus,             // slider-05-reindeer-lavvu
  iceFishing:        local('activities/fishing/ice-fishing-hole.webp'), // pilkkiavanto, ei revontulia
  saunaWinter:       HERO.smokesauna,             // hotels/smoke-sauna-cabin
} as const;

// === Activity → image matcher ===
//
// Match the activity by keyword in title + category and return a relevant
// image. If no keyword matches, fall back to the per-category image (which
// is itself a unique, brand-clean WebP). Never use random hashing — that's
// what produced "snowmobile expedition" cards showing a glass igloo.
//
// When Vesa generates per-activity-type images in a Tier 2 batch, the map
// below grows.

// Order is significant — first match wins, so SPECIFIC keywords come before
// GENERIC ones. e.g. "Polar Bears" must match `bear` before `trail` (which
// might appear in the description) sweeps it to summer-hike.
const KEYWORD_IMAGE: Array<{ match: RegExp; img?: string; imgs?: string[] }> = [
  // Specific named places / cultural items first — Tier 2 imagery where available
  // Heritage / real named places → GENERIC non-claiming theme images (no fabricated building/landmark). Per Vesa 2026-06-22.
  { match: /santa(park)?|christmas|joulu|elf|arctic circle (cross|line|marker)/i,
                                                                        img: local('activities/culture/festive-forest.webp') },
  { match: /gold pan(ning)?|tankavaara/i,                               img: local('activities/culture/gold-panning.webp') },
  { match: /amethyst|lampivaara|mine\b/i,                               img: local('activities/culture/amethyst.webp') },
  { match: /s[íi]ida|samiland/i,                                        img: local('activities/culture/sami-heritage.webp') },
  { match: /arktikum/i,                                                 img: local('activities/culture/arctic-city.webp') },
  { match: /pentik/i,                                                   img: local('activities/culture/ceramics.webp') },
  { match: /museum|m[uu]seo/i,                                          img: local('activities/culture/arctic-city.webp') },
  // Karhunkierros = "Bear's Ring" HIKING trail (summer trek) — NOT wildlife. Must match before /bear/.
  { match: /karhunkierros|bear.?s ring|little bear.?s ring/i,           img: local('heroes/slider-03-summer-hike.webp') },
  // Ranua Zoo genuinely has a polar bear — that's the only correct use of polar-bears.webp.
  { match: /polar bear|ranua/i,                                         img: local('activities/wildlife/polar-bears.webp') },
  // Wolverine/lynx/fox: no dedicated image yet → generic green-summer wilderness (not a bear).
  { match: /wolverine|lynx|fox|arctic hare/i,                           img: local('categories/summer.webp') },
  // Brown-bear watching (Kuusamo) is a SUMMER hide activity — real brown-bear-in-summer image (Gamma GPT Image 2, #83).
  { match: /bear|wildlife/i,                                            img: local('activities/wildlife/brown-bear-summer.webp') },
  // Reindeer & husky each rotate over 2 distinct images so the animals category
  // no longer shows the same reindeer/husky photo on three sibling cards.
  { match: /reindeer|s[áa]mi|lavvu|kota dinner/i,
        imgs: [local('heroes/slider-05-reindeer-lavvu.webp'), local('heroes/reindeer-herd-sunset.webp')] },
  { match: /husky|husk[iy]|sled dog|kennel/i,
        imgs: [local('heroes/slider-01-husky-aurora.webp'), local('heroes/husky-sled-day.webp')] },

  // Sports / activities — BEFORE lodging because activity titles are the strongest
  // signal (a "snowmobile expedition" must match snowmobile even if the description
  // mentions "cabin lunch")
  { match: /snowmobile|kelkka|skidoo/i,
        imgs: [local('heroes/slider-02-snowmobile-fells.webp'), local('heroes/snowmobile-safari.webp'), local('activities/winter/snowmobile-river.webp')] },
  { match: /ice ?kart|go.?kart|karting/i,                              img: local('activities/winter/snowmobile-river.webp') },
  { match: /snowshoe/i,                                                img: local('activities/winter/snowshoe-forest.webp') },
  { match: /fat ?bike/i,                                               img: local('activities/winter/fatbike-snow.webp') },
  // Riisitunturi "tykky" snow-crowned trees = an ICONIC WINTER scene, even though the
  // activity sits in the year-round "Summer Adventures" category. Must match BEFORE the
  // generic /summer/ catch-all (its category string contains "summer") so it does NOT
  // inherit the summer-lake image (owner-reported mismatch 2026-06-26). No dedicated
  // tykky image on disk yet → use the snowy-fell winter scene; FLAGGED for generation.
  { match: /riisitunturi|tykky|snow.?tree|snow.?crown/i,               img: local('heroes/ski-resort-winter.webp') },
  // Frozen-waterfall / ice-climbing BEFORE hike — a frozen Korouoma gorge is a winter ice
  // activity, not a summer hike. ("korouoma" alone dropped: it's a green hiking gorge in summer.)
  { match: /ice climb|frozen waterfall|korouoma/i,                     img: local('activities/adventure/ice-climbing.webp') },
  // Hike BEFORE ski/sauna — hiking is the primary signal; a summer hike whose description
  // mentions a winter cross-country ski route or a Kiilopää sauna must still show a hiking
  // image, not a snowy ski resort or a sauna. ("trail" dropped — it false-matches ski/sled/bike trails.)
  { match: /\bhiking\b|\bhike\b|\btrek\b|fjell hike|fell hike|karhunkierros/i,
        imgs: [local('heroes/slider-03-summer-hike.webp'), local('categories/summer.webp')] },
  { match: /\bski(ing)?\b|slope|piste|biathlon|cross[- ]country|snowboard/i,
        imgs: [local('hotels/fell-resort-levi.webp'), local('heroes/ski-resort-winter.webp'), local('activities/winter/cross-country.webp')] },
  // Aurora is a PRIMARY signal — must beat the generic boat/fish/berry rules below, whose
  // keywords can appear in an aurora tour's English description. Winter-primary rules above still win.
  { match: /aurora|northern light|revontul/i,
        imgs: [local('activities/northern-lights/aurora-lake.webp'), local('activities/northern-lights/aurora-people.webp')] },
  // King crab (Barents Sea, Norway) is a boat/RIB "safari" whose description says
  // "RIB-boat", so it MUST precede the water rules (kayak/boat) AND the ice-fishing rule
  // (the category string "Fishing & Ice Fishing" makes /ice fish/ match it too). Two
  // variants so the pair of Saariselkä king-crab cards never show the same photo.
  { match: /king crab|kongekrabbe|crab safari/i,
        imgs: [local('activities/fishing/fishing-kingcrab.webp'), local('activities/fishing/fishing-kingcrab-2.webp')] },
  { match: /kayak|canoe|paddle|sup\b|raft|river run/i,                  img: local('activities/summer/kayak.webp') },
  { match: /icebreaker|sampo/i,                                        img: local('activities/winter/icebreaker-sampo.webp') },
  { match: /boat|cruise|lake.*tour/i,                                  img: local('activities/summer/lake-cruise.webp') },
  // Kukkolankoski = SUMMER net-fishing at the rapids (Food & Drink). Its title carries
  // "whitefish", but so do the ice-fishing descriptions ("jig for perch and whitefish"),
  // so match the unique place name — never bare /whitefish/ — and give it a river image,
  // not a winter ice one (season-accuracy release gate).
  { match: /kukkolankoski/i,                                           img: local('activities/fishing/fishing-river.webp') },
  { match: /salmon|fly[- ]?fish|tornionjoki|teno river/i,               img: local('activities/summer/salmon-fishing.webp') },
  // Ice fishing (winter) — 3 distinct, season-accurate photos so sibling cards on one
  // destination page (Rovaniemi has three) never repeat. assignActivityImages round-robins them.
  { match: /ice[ -]?fish/i,
        imgs: [local('activities/fishing/fishing-ice.webp'), local('activities/fishing/fishing-ice-day.webp'), local('activities/fishing/fishing-ice-dusk.webp')] },
  { match: /fish(ing)?/i,                                               img: local('activities/fishing/fishing-river.webp') },
  { match: /mountain bike|mtb|cycling|bike park/i,                      img: local('activities/summer/mtb-bikepark.webp') },
  { match: /golf/i,                                                     img: local('activities/summer/golf.webp') },
  { match: /berry|cloudberry|forag|mushroom/i,                          img: local('activities/summer/foraging.webp') },
  { match: /campfire|kota cook|outdoor (cooking|dinner)/i,              img: local('activities/food/campfire-salmon.webp') },

  // Lodging / structures (after sports)
  { match: /glass igloo|aurora cabin|igloo/i,                           img: local('hotels/glass-igloo-aurora.webp') },
  { match: /smoke sauna|savusauna|kiilop[ää]+/i,                        img: local('hotels/smoke-sauna-cabin-saariselka.webp') },
  { match: /ice (hotel|chapel|castle|restaurant|gallery)|snowcastle|snow ?hotel|ice village/i,
                                                                        img: local('activities/culture/ice-architecture.webp') },
  { match: /ice floating|float experience|arctic float/i,               img: local('activities/wellness/ice-floating.webp') },
  { match: /hot tub|wood[- ]fired tub|jacuzzi/i,                        img: local('activities/wellness/spa-hottub.webp') },
  { match: /spa|wellness|massage/i,                                     img: local('activities/wellness/spa-hottub.webp') },
  { match: /float/i,                                                    img: local('activities/wellness/ice-floating.webp') },
  { match: /sauna/i,                                                    img: local('hotels/smoke-sauna-cabin-saariselka.webp') },
  { match: /cabin|log house|lakeside lodge/i,                           img: local('hotels/log-cabin-lakeside.webp') },

  // Generic outdoor
  { match: /midnight sun|summer/i,                                       img: local('categories/summer.webp') },

  // City/destination tour catch-alls
  { match: /city tour|rovaniemi tour|kemi tour|tornio tour/i,           img: local('hotels/boutique-hotel-rovaniemi.webp') },
  // Haparanda border-shopping day (Tornio page) — urban scene, not a nature shot.
  { match: /haparanda|ikea|shopping/i,                                  img: local('hotels/boutique-hotel-rovaniemi.webp') },
];

export interface ActivityImageInput {
  title?: string;
  category?: string;
  categorySlug?: string;
  description?: string;
}

// Deterministic (SSG-safe — no Math.random) pick from a small image set, keyed by
// the activity's text. Same activity → same image every render; sibling cards vary.
function pickStable(key: string, imgs: string[]): string {
  let h = 2166136261;
  for (let i = 0; i < key.length; i++) { h ^= key.charCodeAt(i); h = Math.imul(h, 16777619); }
  return imgs[(h >>> 0) % imgs.length];
}

function hay(act: ActivityImageInput): string {
  return `${act.title || ''} | ${act.category || ''} | ${act.description || ''}`;
}

// Matched keyword entry's index + its image pool (singletons normalised to 1-element).
function matchEntry(act: ActivityImageInput): { idx: number; imgs: string[] } | null {
  const haystack = hay(act);
  for (let i = 0; i < KEYWORD_IMAGE.length; i++) {
    const e = KEYWORD_IMAGE[i];
    if (e.match.test(haystack)) return { idx: i, imgs: e.imgs ?? [e.img!] };
  }
  return null;
}

export function imageForActivity(act: ActivityImageInput | string): string {
  // Backwards-compat: legacy callers passed the id string. Best-effort
  // fallback to category cabin image when only a string is given.
  if (typeof act === 'string') {
    return imageForCategory('adventure');
  }
  const m = matchEntry(act);
  if (m) return m.imgs.length > 1 ? pickStable(hay(act), m.imgs) : m.imgs[0];
  return imageForCategory(act.categorySlug || 'adventure');
}

// List-aware assignment for GRIDS: round-robins each theme's image pool across the
// cards in list order, so multi-image themes (reindeer, husky) strictly alternate and
// never repeat on adjacent cards. Single-call sites keep using imageForActivity.
export function assignActivityImages(acts: ActivityImageInput[]): string[] {
  const counters: Record<number, number> = {};
  return acts.map((act) => {
    const m = matchEntry(act);
    if (!m) return imageForCategory(act.categorySlug || 'adventure');
    if (m.imgs.length === 1) return m.imgs[0];
    const n = (counters[m.idx] = (counters[m.idx] ?? 0) + 1) - 1;
    return m.imgs[n % m.imgs.length];
  });
}

// Automatic seasonal switch — summer 1 May–30 Sep, winter 1 Oct–30 Apr (runtime, every year).
const isSummerSeason = (): boolean => { const m = new Date().getMonth() + 1; return m >= 5 && m <= 9; };
const seasonal = (winter: string, summer: string): string => (isSummerSeason() ? summer : winter);

// Per-category curated hero. Year-round categories flip winter↔summer; topic-specific
// ones (northern-lights, winter-sports, summer) stay fixed; neutral ones (wellness/culture/food) kept.
const CATEGORY_HERO: Record<string, string> = {
  adventure:        seasonal(local('heroes/slider-02-snowmobile-fells.webp'), local('activities/summer/kayak.webp')),
  animals:          seasonal(local('heroes/slider-05-reindeer-lavvu.webp'), local('heroes/reindeer-herd-sunset.webp')),
  'northern-lights': local('activities/northern-lights/aurora-lake.webp'),
  'winter-sports':  local('hotels/fell-resort-levi.webp'),
  wellness:         local('hotels/smoke-sauna-cabin-saariselka.webp'),
  culture:          local('heroes/slider-05-reindeer-lavvu.webp'),
  summer:           local('categories/summer.webp'),
  food:             local('hotels/log-cabin-lakeside.webp'),
  // Distinct from the /fishing GUIDE hero (salmon-fishing.webp): the category grid
  // gets its own seasonal scene — river fishing in summer, ice fishing at dusk in winter.
  fishing:          seasonal(local('activities/fishing/fishing-ice-dusk.webp'), local('activities/fishing/fishing-river.webp')),
};

export function imageForCategory(slug: string): string {
  return CATEGORY_HERO[slug] ?? HERO.huskyAurora;
}

// Per-destination curated hero — UNIQUE per destination.
// Destinations are year-round → all flip winter↔summer (existing pool images).
// UNIQUE hero per destination in BOTH seasons (Vesa 2026-07-07: Levi/Ruka/Posio
// all showed the same summer photo, and Rovaniemi's summer hero was a river
// cityscape — Rovaniemi is marketed Santa-first, always).
const DEST_HERO: Record<string, string> = {
  rovaniemi:  local('heroes/slider-05-reindeer-lavvu.webp'), // Santa/reindeer-first, year-round
  levi:       seasonal(local('hotels/fell-resort-levi.webp'), local('heroes/slider-03-summer-hike.webp')),
  yllas:      seasonal(local('heroes/slider-02-snowmobile-fells.webp'), local('activities/summer/mtb-bikepark.webp')),
  saariselka: seasonal(local('hotels/smoke-sauna-cabin-saariselka.webp'), local('activities/summer/kayak.webp')),
  inari:      seasonal(local('heroes/inari-winter-lake.webp'), local('activities/summer/lake-cruise.webp')),
  ruka:       seasonal(local('heroes/ski-resort-winter.webp'), local('heroes/reindeer-herd-sunset.webp')),
  // Posio = Riisitunturi + Korouoma wilderness. Winter → snowmobile fells; the
  // aurora lake reads as the Posio autumn/lakes mood in the light season.
  posio:      seasonal(local('heroes/husky-sled-day.webp'), local('heroes/posio-summer-lake.webp')),
  tornio:     seasonal(local('activities/culture/arctic-city.webp'), local('activities/summer/salmon-fishing.webp')),
  // New 2026-07-24: dedicated generated heroes (same image both seasons, like rovaniemi).
  'pyha-luosto': local('heroes/pyha-luosto-fells.webp'),
  kemijarvi:  local('heroes/kemijarvi-lake-town.webp'),
};

export function imageForDestination(slug: string): string {
  return DEST_HERO[slug] ?? HERO.huskyAurora;
}

// === Focal point (object-position) — RELEASE GATE ===
//
// Hero images are rendered with `object-cover` into wide, short containers, so
// the top and bottom get cropped. When a subject's head / helmet sits near the
// top edge (e.g. the Ylläs MTB rider), default centre-cropping decapitates them.
// This map pins a safe `object-position` per image so heads/helmets are NEVER
// cut at any breakpoint. Default is 'center 35%' (slightly high) which keeps
// horizons and most subjects framed; override per file where the subject is
// high or low in frame. Owner finding 2026-06-26 — now a standard release gate.
const FOCAL: Record<string, string> = {
  // Subject's head/helmet is near the TOP → anchor higher so it's never cropped.
  '/images/activities/summer/mtb-bikepark.webp': 'center 22%',
  '/images/activities/summer/salmon-fishing.webp': 'center 38%',
  '/images/activities/fishing/fishing-river.webp': 'center 45%',
  '/images/activities/fishing/fishing-ice-dusk.webp': 'center 45%',
  // Wide aurora arcs read best with the sky kept — anchor a touch low.
  '/images/heroes/slider-01-husky-aurora.webp': 'center 42%',
  '/images/og/og-default.webp': 'center 45%',
  // Reindeer herd walks along the lower third → keep animals in frame.
  '/images/heroes/reindeer-herd-sunset.webp': 'center 40%',
  '/images/heroes/slider-05-reindeer-lavvu.webp': 'center 45%',
  // Snowmobile rider sits at mid-right; default centre is fine but nudge up.
  '/images/heroes/slider-02-snowmobile-fells.webp': 'center 42%',
  '/images/heroes/snowmobile-safari.webp': 'center 40%',
  // Hikers stand on the ridge in the vertical centre.
  '/images/heroes/slider-03-summer-hike.webp': 'center 45%',
  // Fell resort village sits low → keep it visible.
  '/images/hotels/fell-resort-levi.webp': 'center 55%',
  '/images/heroes/ski-resort-winter.webp': 'center 45%',
  // Summer lake: paddler + sun are in the lower-mid → anchor low.
  '/images/categories/summer.webp': 'center 55%',
  // New destination heroes: pyha fell tops sit mid-high; kemijarvi town+train band
  // is in the UPPER third (frozen lake fills the lower two thirds) → anchor high.
  '/images/heroes/pyha-luosto-fells.webp': 'center 40%',
  '/images/heroes/kemijarvi-lake-town.webp': 'center 30%',
};

/** Safe object-position for a hero image so heads/helmets are never cropped. */
export function focalFor(src: string): string {
  return FOCAL[src] ?? 'center 35%';
}
