// All imagery is locally hosted in /public/images/. WebP optimized via
// scripts/optimize-images.mjs. No Google Drive, no Unsplash, no third-party CDN.
//
// 19.9.2026: AI-kuvat korvattu oikeilla valokuvilla (omat heinäkuun 2026 kuvat + Wikimedia Commons).
// Kuitit: src/data/photoCredits.ts, nimetyt kohteet public/images/KUVALAHTEET.json. AI-alkuperäiset:
// monorepo _reissu-2026-07/_ai-originals-backup/laplandactivities-new/. Sliderin kuvat 01/02/05 ovat
// nyt Commons-valokuvia (Saija husky, Inari kelkka, Kemi porokyyti), 04 lasi-iglut Inari, 07 melonta Inari.
//
// CURATED HIGH-RES POOL (12 images, brand-clean, all WebP, generated by Vesa):
//   /heroes/slider-01-husky-aurora.webp        (husky team + aurora)
//   /heroes/slider-02-snowmobile-fells.webp    (snowmobile + fjells)
//   /heroes/slider-03-summer-hike.webp         (oma: Rukan gondoli kesämetsän yllä 17.7.2026; nimi historiallinen)
//   /heroes/slider-04-glass-igloo.webp         (glass igloo, twilight)
//   /heroes/slider-05-reindeer-lavvu.webp      (reindeer + Sámi lavvu)
//   /categories/summer.webp                    (summer landscape, vertical-friendly)
//   /hotels/glass-igloo-aurora.webp            (single igloo + aurora)
//   /hotels/log-cabin-lakeside.webp            (red log cabin, lakeside)
//   /heroes/levi-black-run-view.webp           (Levi, näkymä Black-rinteen yläpäästä)
//   /hotels/boutique-hotel-rovaniemi.webp      (modern hotel exterior)
//   /activities/wellness/smoke-sauna-siida-inari.webp  (savusauna, Siidan ulkomuseo, Inari)
//   /og/og-default.webp                        (wide aurora composition for OG)

import { currentSeason } from '../i18n/seasonWords';

const local = (file: string) => `/images/${file}`;

// 🔴 Kausikuva = SAMA kalenteri kuin tekstit (currentSeason, src/i18n/seasonWords.ts).
// 23.9.2026 asti tassa oli oma saanto (kesa touko-syys, talvi loka-huhti), joten
// lokakuussa kuva oli luminen kun teksti sanoi "syksy" ja lumi tulee marraskuussa.
// Lumikuva vain talvella (11-4). Syksylla oma ruskakuva jos annettu, muuten lumeton.
const seasonal = (winter: string, summer: string, autumn?: string): string => {
  const s = currentSeason();
  if (s === 'winter') return winter;
  if (s === 'autumn' && autumn) return autumn;
  return summer;
};

// === SAFE / CONFIRMED-CLEAN HIGH-RES POOL ===
// 🔴🔴 2026-08-23: tama lohko VAITTI ennen etta "every alias maps to a UNIQUE
// entry ... guarantees no two surfaces share the same image at the same time".
// Se ei pitanyt paikkaansa, ja juuri se vakuutus piilotti ongelman. Mitattuna
// renderoidylta etusivulta: slider-03 x3, slider-05 x3, fell-resort-levi x3 (nyt levi-black-run-view),
// og-default x3, ja viisi muuta x2. Aliaksia on enemman kuin kuvia, joten osa
// niista OSOITTAA VALTTAMATTA samaan tiedostoon.
//
// 🔴 og/og-default.webp on sosiaalisen jaon kuva. Se oli kortin kuvana
// yhdeksassa eri lupauksessa (revontulet x2, Sampo-jaanmurtaja, pilkkiminen,
// lapset lumessa, jainen jarvi, Inari talvella, Posio kesalla). Nyt jokaisella
// on oma kuva. ALA koskaan laita og-defaultia takaisin sisaltokuvaksi - se on
// merkki siita etta kuva puuttuu, ei kuva.
//
// Oikea sanamuoto: alla oleva allas on brandipuhdas ja paikallinen, mutta se ei
// riita kattamaan kaikkia pintoja. Jos tarvitset uuden kortin, TEE UUSI KUVA.

export const HERO = {
  // Primary aurora — used in newsletter popup decoration etc.
  aurora:           local('activities/northern-lights/aurora-lake.webp'),

  // Used by destinations.ts / categories.ts via legacy alias names
  auroraLake:       local('activities/northern-lights/aurora-lake.webp'), // aurora + jaatynyt jarvi
  snowyForest:      local('heroes/slider-02-snowmobile-fells.webp'), // wide forest+sled
  huskyAurora:      local('heroes/slider-01-husky-aurora.webp'),
  huskySnowmobile:  local('heroes/slider-02-snowmobile-fells.webp'),
  campfire:         local('hotels/log-cabin-lakeside.webp'),         // cabin + outdoor
  glassIgloo:       local('heroes/slider-04-glass-igloo.webp'),

  // Legacy alias names (used by destinations.ts) — all now map to high-res WebPs
  santaClaus:       local('activities/culture/santa-village.webp'),
  reindeerHerd:     local('heroes/slider-05-reindeer-lavvu.webp'),
  huskyTeam:        local('heroes/slider-01-husky-aurora.webp'),
  kidsSnow:         local('heroes/winter-band-snowmobile-trail.webp'),
  cabin:            local('hotels/log-cabin-lakeside.webp'),
  iceLake:          local('heroes/inari-winter-lake.webp'),
  fells:            local('heroes/levi-black-run-view.webp'),
  midnightSun:      local('heroes/levi-summer-fell.webp'),          // oma: Levitunturin kesäpanoraama 20.7.2026
  // 🔴 23.9.2026: tassa oli Utsjoen savusaunan kiuas nimella "smoke-sauna-cabin-saariselka",
  // ja SAMA Commons-kuva oli laplandwellnessin saunasivulla. Kaksi vikaa: kuva ei saa
  // olla kahdella sivustolla, ja tiedostonimi valehteli paikan (inventaario r. 257 kieltaa
  // juuri sen). Kiilopaan savusaunasta ei ole yhtaan vapaata kuvaa (Commons haettu
  // luokittain 23.9.), joten tilalla on oikea Lapin savusauna, ja kuvakuitti nimeaa paikan.
  smokesauna:       local('activities/wellness/smoke-sauna-siida-inari.webp'),
  fjell:            local('heroes/slider-02-snowmobile-fells.webp'),
  village:          local('hotels/boutique-hotel-rovaniemi.webp'),

  // Animal-experience card variety — derived from existing in-repo Drive imagery
  // (hero_01 / mkt_04), downscaled to WebP+AVIF. Feeds the reindeer/husky rotation
  // so sibling cards no longer repeat the same single image.
  reindeerSunset:   local('heroes/reindeer-herd-sunset.webp'),  // reindeer herd, golden sunset
  huskyDay:         local('heroes/husky-sled-day.webp'),        // daytime husky-sled team
  skiResortWinter:  local('heroes/pyha-winter-slopes.webp'),     // Pyhätunturi, Commons (kallerna)
  ruskaRidge:       local('activities/summer/oulanka-ruska-trail.webp'), // Commons: Karhunkierros ruskassa (Ninara CC BY 2.0)
  salmonFishing:    local('activities/summer/salmon-fishing.webp'), // river salmon fishing, used by fishing category hero

  // 2026-08-30: both destination heroes are now REAL photos from the July 2026 road trip
  // (was Picsart AI 2026-07-24; AI originals in monorepo _reissu-2026-07/_ai-originals-backup/).
  pyhaLuosto:       local('heroes/pyha-luosto-fells.webp'),     // real: summer fell panorama from Pyhä summit, 19.7.2026
  kemijarvi:        local('heroes/kemijarvi-lake-town.webp'),   // real: mirror-calm Kemijärvi at golden hour, 18.7.2026
} as const;

// HERO_BRANDED — kept as alias for legacy data references
export const HERO_BRANDED = {
  magicOfLapland:  HERO.glassIgloo,
  gatewayLapland:  HERO.village,
  discoverLapland: HERO.huskySnowmobile,
  tasteArctic:     HERO.smokesauna,
  distinctive:     HERO.huskyAurora,
  homeArctic:      HERO.cabin,
  relaxRecharge:   HERO.smokesauna,
} as const;

// MKT pool — used by categories.ts. Each key maps to a UNIQUE high-res file.
export const MKT = {
  huskyAuroraFamily: HERO.huskyAurora,            // slider-01
  huskySnowmobile:   HERO.huskySnowmobile,        // slider-02
  huskyAurora:       HERO.huskyAurora,            // slider-01
  huskyDaylight:     HERO.huskySnowmobile,        // slider-02
  campfireNight:     HERO.cabin,                  // log-cabin-lakeside
  campfireClose:     HERO.cabin,
  campfireTripod:    HERO.cabin,
  campfireStars:     HERO.cabin,
  igluCouple:        HERO.glassIgloo,             // hotels/glass-igloo-aurora
  igluAurora:        HERO.glassIgloo,
  igluClose:         HERO.glassIgloo,
  igluDramatic:      HERO.glassIgloo,
  reindeerSled:      HERO.santaClaus,             // slider-05-reindeer-lavvu
  iceFishing:        local('activities/fishing/ice-fishing-hole.webp'), // pilkkiavanto, ei revontulia
  saunaWinter:       HERO.smokesauna,             // savusauna, Siida, Inari
} as const;

// === Activity → image matcher ===
//
// Match the activity by keyword in title + category and return a relevant
// image. If no keyword matches, fall back to the per-category image (which
// is itself a unique, brand-clean WebP). Never use random hashing — that's
// what produced "snowmobile expedition" cards showing a glass igloo.
//
// When Vesa generates per-activity-type images in a Tier 2 batch, the map
// below grows.

// Order is significant — first match wins, so SPECIFIC keywords come before
// GENERIC ones. e.g. "Polar Bears" must match `bear` before `trail` (which
// might appear in the description) sweeps it to summer-hike.
const KEYWORD_IMAGE: Array<{ match: RegExp; img?: string; imgs?: string[] }> = [
  // Specific named places / cultural items first — Tier 2 imagery where available
  // Heritage / real named places → GENERIC non-claiming theme images (no fabricated building/landmark). Per Vesa 2026-06-22.
  { match: /little village|uitonniemi/i,                                img: local('activities/culture/santas-little-village.webp') },
  { match: /santa(park)?|christmas|joulu|elf|arctic circle (cross|line|marker)/i,
                                                                        img: seasonal(local('activities/culture/santa-village-winter.webp'), local('activities/culture/santa-village.webp')) },
  { match: /gold pan(ning)?|tankavaara/i,                               img: local('activities/culture/gold-panning.webp') },
  { match: /amethyst|lampivaara|mine\b/i,                               img: local('activities/culture/amethyst.webp') },
  { match: /s[íi]ida/i,                                                 img: local('activities/culture/sami-heritage.webp') },
  { match: /samiland/i,                                                 img: local('activities/culture/sami-duodji.webp') },
  { match: /arktikum/i,                                                 img: local('activities/culture/arctic-city.webp') },
  { match: /pentik/i,                                                   img: local('activities/culture/ceramics.webp') },
  { match: /museum|m[uu]seo/i,                                          img: local('activities/culture/arctic-city.webp') },
  // Karhunkierros = "Bear's Ring" HIKING trail (summer trek) — NOT wildlife. Must match before /bear/.
  { match: /karhunkierros|bear.?s ring|little bear.?s ring/i,           img: local('activities/summer/oulanka-ruska-trail.webp') },
  { match: /raft|river run|kitkajoki/i,                                 img: local('activities/adventure/kitkajoki-rapids.webp') },
  // Ranua Zoo genuinely has a polar bear — that's the only correct use of polar-bears.webp.
  { match: /polar bear|ranua/i,                                         img: local('activities/wildlife/polar-bears.webp') },
  // Wolverine/lynx/fox: no dedicated image yet → generic green-summer wilderness (not a bear).
  { match: /wolverine|lynx|fox|arctic hare/i,                           img: local('categories/summer.webp') },
  // Brown-bear watching (Kuusamo) is a SUMMER hide activity — real brown-bear-in-summer image (Gamma GPT Image 2, #83).
  { match: /bear|wildlife/i,                                            img: local('activities/wildlife/brown-bear-summer.webp') },
  // Reindeer & husky each rotate over 2 distinct images so the animals category
  // no longer shows the same reindeer/husky photo on three sibling cards.
  { match: /reindeer|s[áa]mi|lavvu|kota dinner/i,
        imgs: [local('heroes/reindeer-winter.webp'), local('heroes/reindeer-herd-sunset.webp'), local('activities/winter/reindeer-farm-inari.webp'), local('activities/winter/reindeer-sleds-inari.webp'), local('activities/summer/reindeer-kilpisjarvi.webp'), local('activities/summer/reindeer-saytsjarvi.webp')] },
  // imgs[0] EI ole slider-01: se on hero-sliderin kuva, ja huskykortti nayttaisi
  // etusivulla saman kuvan kahdesti (mitattu 2026-08-23).
  { match: /husky|husk[iy]|sled dog|kennel/i,
        imgs: [local('activities/winter/husky-kennel.webp'), local('activities/winter/sled-dogs-lapland.webp'), local('activities/winter/husky-ride-ruka.webp'), local('activities/winter/husky-dogs-ruka.webp'), local('activities/winter/husky-ready-ruka.webp')] },

  // Sports / activities — BEFORE lodging because activity titles are the strongest
  // signal (a "snowmobile expedition" must match snowmobile even if the description
  // mentions "cabin lunch")
  // imgs[0] EI ole slider-02: sama syy kuin huskylla.
  { match: /snowmobile|kelkka|skidoo/i,
        imgs: [local('activities/winter/snowmobile-river.webp'), local('activities/winter/snowmobile-ruka-lake.webp'), local('activities/winter/snowmobile-kuntivaara.webp'), local('activities/winter/snowmobile-ruka-forest.webp'), local('activities/winter/snowmobile-saariselka.webp')] },
  { match: /ice ?kart|go.?kart|karting/i,                              img: local('heroes/inari-winter-lake.webp') },
  { match: /arctic snow ?hotel/i,                                       img: local('activities/winter/ounasvaara-winter.webp') },
  { match: /snow ?village|lainio/i,                                     img: local('activities/culture/snow-village.webp') },
  { match: /snowcastle|snow castle|lumilinna/i,                         img: local('activities/culture/snowcastle-kemi.webp') },
  { match: /snowshoe/i,                                                img: local('activities/winter/snowshoe-forest.webp') },
  { match: /fat ?bike/i,                                               img: local('activities/winter/fatbike-snow.webp') },
  // Riisitunturi "tykky" snow-crowned trees = an ICONIC WINTER scene, even though the
  // activity sits in the year-round "Summer Adventures" category. Must match BEFORE the
  // generic /summer/ catch-all (its category string contains "summer") so it does NOT
  // inherit the summer-lake image (owner-reported mismatch 2026-06-26). No dedicated
  // tykky image on disk yet → use the snowy-fell winter scene; FLAGGED for generation.
  { match: /pyh[äa]-luosto national park|isokuru/i,                      img: local('activities/winter/pyha-summer-lift.webp') },
  { match: /riisitunturi|tykky|snow.?tree|snow.?crown/i,               img: local('activities/summer/riisitunturi-tykky.webp') },
  // Frozen-waterfall / ice-climbing BEFORE hike — a frozen Korouoma gorge is a winter ice
  // activity, not a summer hike. ("korouoma" alone dropped: it's a green hiking gorge in summer.)
  { match: /ice climb|frozen waterfall|korouoma/i,
        imgs: [local('activities/adventure/korouoma-frozen.webp'), local('activities/adventure/ice-climbing.webp')] },
  { match: /pallas/i,                                                   img: local('activities/summer/pallas-fells.webp') },
  { match: /urho kekkonen|kiilop/i,                                     img: local('activities/summer/kiilopaa-view-east.webp') },
  { match: /pielpaj/i,                                                  img: local('heroes/inari-summer-lake.webp') },
  { match: /ounasvaara/i,                                               img: local('activities/winter/ounasvaara-winter.webp') },
  { match: /ruka ski|rukatunturi/i,                                     img: local('heroes/ruka-winter-slopes.webp') },
  { match: /yll[äa]s ski|yll[äa]stunturi/i,                             img: local('heroes/yllas-winter-road.webp') },
  { match: /pyh[äa] ski|pyh[äa]tunturi/i,                               img: local('heroes/pyha-winter-slopes.webp') },
  { match: /levi ski|levitunturi/i,                                     img: local('activities/winter/levi-north-slope.webp') },
  // Hike BEFORE ski/sauna — hiking is the primary signal; a summer hike whose description
  // mentions a winter cross-country ski route or a Kiilopää sauna must still show a hiking
  // image, not a snowy ski resort or a sauna. ("trail" dropped — it false-matches ski/sled/bike trails.)
  { match: /\bhiking\b|\bhike\b|\btrek\b|fjell hike|fell hike|karhunkierros/i,
        imgs: [local('categories/summer.webp'), local('activities/summer/pallas-fells.webp')] },
  { match: /\bski(ing)?\b|slope|piste|biathlon|cross[- ]country|snowboard/i,
        imgs: [local('activities/winter/ounasvaara-slope-april.webp'), local('heroes/pyha-winter-slopes.webp'), local('activities/winter/cross-country.webp'), local('activities/winter/levi-piste1.webp'), local('activities/winter/downhill-skiers.webp'), local('heroes/levi-black-run-view.webp')] },
  // Aurora is a PRIMARY signal — must beat the generic boat/fish/berry rules below, whose
  // keywords can appear in an aurora tour's English description. Winter-primary rules above still win.
  { match: /aurora|northern light|revontul/i,
        // 🔴 Pooli oli KAKSI kuvaa seitsemalle revontulikortille, joten sama kuva
        // toistui kolmesti. Kolme uutta Lapin revontulikuvaa (Levi, Inari) laajentaa
        // poolin viiteen. Vesa 21.9.: "joku kuva pakko olla" — toisto on parempi kuin
        // tyhja kortti, mutta oikea korjaus on lisata kuvia.
        imgs: [local('activities/northern-lights/aurora-lake.webp'), local('activities/northern-lights/aurora-inari-juutuanvuono.webp'), local('activities/northern-lights/aurora-enontekio-hetta.webp'), local('activities/northern-lights/aurora-inari-bands.webp'), local('activities/northern-lights/aurora-levi-bands.webp')] },
  // King crab (Barents Sea, Norway) is a boat/RIB "safari" whose description says
  // "RIB-boat", so it MUST precede the water rules (kayak/boat) AND the ice-fishing rule
  // (the category string "Fishing & Ice Fishing" makes /ice fish/ match it too). Two
  // variants so the pair of Saariselkä king-crab cards never show the same photo.
  { match: /king crab|kongekrabbe|crab safari/i,
        imgs: [local('activities/fishing/fishing-kingcrab.webp'), local('activities/fishing/fishing-kingcrab-2.webp')] },
  { match: /kayak|canoe|paddle|sup\b/i,                                img: local('activities/summer/kayak-inari.webp') },
  { match: /icebreaker|sampo/i,                                        img: local('activities/winter/icebreaker-sampo.webp') },
  { match: /boat|cruise|lake.*tour/i,                                  img: local('activities/summer/lake-cruise.webp') },
  // Kukkolankoski = SUMMER dipnet fishing at the rapids (Food & Drink). Its title carries
  // "whitefish", but so do the ice-fishing descriptions ("jig for perch and whitefish"),
  // so match the unique place name — never bare /whitefish/ — and give it a river image,
  // not a winter ice one (season-accuracy release gate).
  { match: /kukkolankoski/i,                                           img: local('activities/fishing/kukkolankoski.webp') },
  { match: /teno|tana river|utsjoki/i,                                  img: local('activities/fishing/teno-valley.webp') },
  { match: /salmon|fly[- ]?fish|tornionjoki|teno river/i,               img: local('activities/summer/salmon-fishing.webp') },
  // Ice fishing (winter) — 3 distinct, season-accurate photos so sibling cards on one
  // destination page (Rovaniemi has three) never repeat. assignActivityImages round-robins them.
  { match: /ice[ -]?fish/i,
        imgs: [local('activities/fishing/fishing-ice.webp'), local('activities/fishing/ice-fishing-hole.webp'), local('activities/fishing/fishing-ice-day.webp')] },
  { match: /fish(ing)?/i,                                               img: local('activities/fishing/fishing-river.webp') },
  { match: /mountain bike|mtb|cycling|bike park/i,                      img: local('activities/summer/mtb-bikepark.webp') },
  { match: /golf/i,                                                     img: local('activities/summer/golf.webp') },
  { match: /berry|cloudberry|forag|mushroom/i,                          img: local('activities/summer/foraging.webp') },
  { match: /campfire|kota cook|kammi|outdoor (cooking|dinner)/i,
        imgs: [local('activities/food/campfire-salmon.webp'), local('activities/food/salmon-plate.webp')] },

  // Lodging / structures (after sports)
  { match: /glass igloo|aurora cabin|igloo/i,                           img: local('heroes/slider-04-glass-igloo.webp') },
  { match: /smoke sauna|savusauna|kiilop[ää]+/i,                        img: local('activities/wellness/smoke-sauna-siida-inari.webp') },
  { match: /ice (hotel|chapel|castle|restaurant|gallery)|snowcastle|snow ?hotel|ice village/i,
                                                                        img: local('activities/culture/ice-architecture.webp') },
  { match: /ice floating|float experience|arctic float/i,               img: local('activities/wellness/ice-floating.webp') },
  { match: /hot tub|wood[- ]fired tub|jacuzzi/i,                        img: local('activities/wellness/spa-hottub.webp') },
  { match: /spa|wellness|massage/i,                                     img: local('activities/wellness/spa-hottub.webp') },
  { match: /float/i,                                                    img: local('activities/wellness/ice-floating.webp') },
  { match: /sauna/i,                                                    img: local('activities/wellness/sauna-interior.webp') },
  { match: /cabin|log house|lakeside lodge/i,                           img: local('hotels/log-cabin-lakeside.webp') },

  // Generic outdoor
  { match: /midnight sun|summer/i,                                       img: local('categories/summer.webp') },

  // City/destination tour catch-alls
  { match: /city tour|rovaniemi tour|kemi tour|tornio tour/i,           img: local('hotels/boutique-hotel-rovaniemi.webp') },
  // Haparanda border-shopping day (Tornio page) — urban scene, not a nature shot.
  { match: /haparanda|ikea|shopping/i,                                  img: local('heroes/tornio-river-dusk.webp') },
];

export interface ActivityImageInput {
  title?: string;
  category?: string;
  categorySlug?: string;
  description?: string;
}

// Deterministic (SSG-safe — no Math.random) pick from a small image set, keyed by
// the activity's text. Same activity → same image every render; sibling cards vary.
function pickStable(key: string, imgs: string[]): string {
  let h = 2166136261;
  for (let i = 0; i < key.length; i++) { h ^= key.charCodeAt(i); h = Math.imul(h, 16777619); }
  return imgs[(h >>> 0) % imgs.length];
}

function hay(act: ActivityImageInput): string {
  return `${act.title || ''} | ${act.category || ''} | ${act.description || ''}`;
}

// Matched keyword entry's index + its image pool (singletons normalised to 1-element).
function matchEntry(act: ActivityImageInput): { idx: number; imgs: string[] } | null {
  const haystack = hay(act);
  for (let i = 0; i < KEYWORD_IMAGE.length; i++) {
    const e = KEYWORD_IMAGE[i];
    if (e.match.test(haystack)) return { idx: i, imgs: e.imgs ?? [e.img!] };
  }
  return null;
}

export function imageForActivity(act: ActivityImageInput | string): string {
  // Backwards-compat: legacy callers passed the id string. Best-effort
  // fallback to category cabin image when only a string is given.
  if (typeof act === 'string') {
    return imageForCategory('adventure');
  }
  const m = matchEntry(act);
  if (m) return m.imgs.length > 1 ? pickStable(hay(act), m.imgs) : m.imgs[0];
  return imageForCategory(act.categorySlug || 'adventure');
}

// List-aware assignment for GRIDS: round-robins each theme's image pool across the
// cards in list order, so multi-image themes (reindeer, husky) strictly alternate and
// never repeat on adjacent cards. Single-call sites keep using imageForActivity.
export function assignActivityImages(acts: ActivityImageInput[], heroImg?: string): string[] {
  // 🔴🔴 EI KOSKAAN TYHJAA KORTTIA. Vesa 21.9.2026: *"ja mitä nämä on ilman kuvia?
  // joku kuva pakko olla"* — revontulikategoriassa kolme korttia jai gradientille,
  // koska tama funktio kieltaytyi toistamasta kuvaa kun uniikit loppuivat. Se oli
  // MINUN virhearvioni samana paivana: valitsin tyhjan kortin duplikaatin sijaan.
  // Oikea jarjestys on:
  //   1. uniikki kuva omasta poolista
  //   2. jos ne loppuvat, VAHITEN kaytetty kuva poolista (toisto)
  //   3. vasta jos poolia ei ole lainkaan, kategorian oma kuva
  // Sivun hero varataan yha ensin, joten hero ei paady kortiksi ellei muuta ole.
  const kaytto = new Map<string, number>();
  if (heroImg) kaytto.set(heroImg, 1);
  const ota = (ehdokkaat: string[]): string => {
    let paras = ehdokkaat[0];
    let vahiten = Infinity;
    for (const e of ehdokkaat) {
      const n = kaytto.get(e) ?? 0;
      if (n < vahiten) { vahiten = n; paras = e; }
      if (n === 0) break; // ensimmainen kayttamaton riittaa
    }
    kaytto.set(paras, (kaytto.get(paras) ?? 0) + 1);
    return paras;
  };
  const counters: Record<number, number> = {};
  return acts.map((act) => {
    const m = matchEntry(act);
    if (!m) return ota([imageForCategory(act.categorySlug || 'adventure')]);
    // Aloitetaan siita kuvasta jonka kierratys antaisi, jotta jarjestys sailyy.
    const n = (counters[m.idx] = (counters[m.idx] ?? 0) + 1) - 1;
    const jarjestys = m.imgs.map((_, i) => m.imgs[(n + i) % m.imgs.length]);
    return ota(jarjestys);
  });
}

// Per-category curated hero. Year-round categories flip winter↔summer; topic-specific
// ones (northern-lights, winter-sports, summer) stay fixed; neutral ones (wellness/culture/food) kept.
const CATEGORY_HERO: Record<string, string> = {
  // Kesä: oma kuva, sähköfatbike Pyhän polulla 19.7.2026 (kayak.webp-nimi on historiallinen)
  // Kesä: oma kuva Levi Bike Parkin portilta 20.7.2026 (Vesa 19.9.: Pyhän sähköfatbike-kuvaa "ei käytetä")
  // 🔴🔴 Kesahero oli Levi Bike Parkin portti, mutta kategoriassa ei ole yhtaan
  // pyorailyaktiviteettia (14 kpl: 13 talvea + 1 koskenlasku, mitattu 21.9.2026).
  // Hero lupasi lajin jota sivu ei tarjoa. Nyt kesalla nakyy se yksi kesalaji joka
  // kategoriassa on: Kitkajoen kosket. Pyorakuva jaa kayttoon siella missa
  // pyorailyaktiviteetti oikeasti on (matchEntry: /mountain bike|mtb|cycling/).
  adventure:        seasonal(local('activities/adventure/korouoma-frozen.webp'), local('activities/adventure/kitkajoki-rapids.webp')),
  animals:          seasonal(local('heroes/reindeer-winter.webp'), local('heroes/reindeer-herd-sunset.webp')),
  'northern-lights': local('activities/northern-lights/aurora-lake.webp'),
  // 🔴 Oli tyhja sumuinen rinne ilman yhtaan laskijaa (Vesa 21.9.2026: "tassa voisi
  // nakya talviurheilu ... jotain kumparelaskua tms"). Nyt kumparelaskua actionilla.
  // 🔴 23.9.2026: tassa oli Commonsin 'Ben Cavet skiing the moguls' — NIMETTY brittilainen
  // kilpailija, ei Lappia, ja nimi nakyi sivuston kuvaluettelossa. Kaupallisen sivun paakuvana
  // nimetty urheilija nayttaa suosittelijalta. Tilalle Pexels 3714137 (Volker Meyer, 2020):
  // kasvot kyparan ja lasien takana, taustalla vain taivas, joten kuva ei vaita paikkaa.
  'winter-sports':  local('activities/winter/skier-powder-carve.webp'),
  // Oma kuva: Grand Hotel Mustaparran sauna, Tornio 21.7.2026 (paikaton pinta, ei väitä kohdetta)
  // 🔴 Kausikohtainen 21.9.2026: kesalla Morgamojan eramaasauna (Inari), talvella
  // LV:n OMA kuva Mustaparran saunasta (Tornio). Oma valokuva sailyy siella missa
  // se toimii, eika kesainen ulkokuva ole ruudulla tammikuussa.
  wellness:         seasonal(local('activities/wellness/sauna-interior.webp'), local('activities/wellness/wilderness-sauna-morgamoja.webp')),
  culture:          local('activities/culture/sami-duodji.webp'),
  // SummerBand kayttaa categories/summer.webp:ia, joten kategoriakortti tarvitsee oman.
  summer:           local('activities/summer/lapland-river.webp'),
  // Oma kuva: savukala-annos Kuusamon Portissa 16.7.2026
  food:             local('activities/food/lapland-plate.webp'),
  // Distinct from the /fishing GUIDE hero (salmon-fishing.webp): the category grid
  // gets its own seasonal scene — river fishing in summer, ice fishing at dusk in winter.
  fishing:          seasonal(local('activities/fishing/fishing-ice.webp'), local('activities/fishing/fishing-river.webp')),
};

export function imageForCategory(slug: string): string {
  return CATEGORY_HERO[slug] ?? HERO.huskyAurora;
}

// Per-destination curated hero — UNIQUE per destination.
// Destinations are year-round → all flip winter↔summer (existing pool images).
// UNIQUE hero per destination in BOTH seasons (Vesa 2026-07-07: Levi/Ruka/Posio
// all showed the same summer photo, and Rovaniemi's summer hero was a river
// cityscape — Rovaniemi is marketed Santa-first, always).
const DEST_HERO: Record<string, string> = {
  // Kesä: oma kuva Joulupukin pajakylän aukiolta 20.7.2026. Talvi: AI kunnes Commons-kuva valittu.
  rovaniemi:  seasonal(local('heroes/rovaniemi-winter-village.webp'), local('heroes/rovaniemi-summer-santa.webp')),
  levi:       seasonal(local('heroes/levi-black-run-view.webp'), local('heroes/levi-summer-fell.webp')),
  // Kesä: oma kuva Äkäslompolon yli Ylläkseltä 21.7.2026 (ennen Levin bike park -kuva = väärä paikka)
  yllas:      seasonal(local('heroes/yllas-winter-road.webp'), local('heroes/yllas-summer-village.webp')),
  // Saariselka: sama kuva molemmissa kausissa (kuten rovaniemi/pyha-luosto). Talvipaikka
  // oli savusaunakuva, joka on wellness-kategorian kuva, ja kesapaikka kajakki, joka on
  // seikkailukategorian kuva - eli kumpikin kausi oli duplikaatti etusivulla.
  saariselka: seasonal(local('heroes/saariselka-winter.webp'), local('activities/summer/kiilopaa-view-east.webp')),
  inari:      seasonal(local('heroes/inari-winter-lake.webp'), local('heroes/inari-summer-lake.webp')),
  // Ruka: kesapaikka oli porolauma, joka on elainkategorian kuva. Oma tunturikuva.
  ruka:       seasonal(local('heroes/ruka-winter-slopes.webp'), local('heroes/ruka-fell.webp')),
  // Posio = Riisitunturi + Korouoma wilderness. Winter → snowmobile fells; the
  // aurora lake reads as the Posio autumn/lakes mood in the light season.
  posio:      seasonal(local('heroes/posio-winter-tykky.webp'), local('heroes/posio-summer-lake.webp')),
  // Kesä: oma kuva Tornionjoelta kirkontornin kanssa 21.7.2026 (salmon-fishing jää kalastusoppaalle)
  tornio:     seasonal(local('activities/culture/snowcastle-kemi.webp'), local('heroes/tornio-river-dusk.webp')),
  // New 2026-07-24: dedicated generated heroes (same image both seasons, like rovaniemi).
  'pyha-luosto': seasonal(local('heroes/pyha-winter-slopes.webp'), local('heroes/pyha-luosto-fells.webp')),
  kemijarvi:  local('heroes/kemijarvi-lake-town.webp'),
};

export function imageForDestination(slug: string): string {
  return DEST_HERO[slug] ?? HERO.huskyAurora;
}

// === Focal point (object-position) — RELEASE GATE ===
//
// Hero images are rendered with `object-cover` into wide, short containers, so
// the top and bottom get cropped. When a subject's head / helmet sits near the
// top edge (e.g. the Ylläs MTB rider), default centre-cropping decapitates them.
// This map pins a safe `object-position` per image so heads/helmets are NEVER
// cut at any breakpoint. Default is 'center 35%' (slightly high) which keeps
// horizons and most subjects framed; override per file where the subject is
// high or low in frame. Owner finding 2026-06-26 — now a standard release gate.
const FOCAL: Record<string, string> = {
  // 26.9.2026: CC BY-SA -kuvat ovat nyt RAJAAMATTOMIA (rajaus = muokattu teos, SA-velvoite).
  // Vanhat tiedostot olivat 16:9-rajauksia, joten jokaiselle laskettiin ankkuri, joka nayttaa
  // 2,5:1-kaistassa (alasivujen herot ja korttikaistat) saman alueen kuin vanha tiedosto ja sen
  // aiempi ankkuri. Ilman riviä oletus 35 % nayttaisi korkeammasta kuvasta liikaa taivasta.
  // Lumilinnan 55 % pitaa lipun LUMILINNA-tekstin 16:9-kehyksen ylapuolella; Jatkankynttilan
  // panoraamassa 80 % pitaa K-Citymarketin pylvaan ja Lapland Safarisin kyltin (vasen 0-13 %) ulkona.
  '/images/activities/adventure/ice-climbing.webp': 'center 43%',
  '/images/activities/adventure/kitkajoki-rapids.webp': 'center 48%',
  '/images/activities/culture/ice-architecture.webp': 'center 43%',
  '/images/activities/culture/santa-village-winter.webp': 'center 41%',
  '/images/activities/fishing/fishing-kingcrab-2.webp': 'center 43%',
  '/images/activities/fishing/fishing-kingcrab.webp': 'center 42%',
  '/images/activities/fishing/kukkolankoski.webp': 'center 41%',
  '/images/activities/fishing/luttojoki.webp': 'center 43%',
  '/images/activities/food/campfire-salmon.webp': 'center 44%',
  '/images/activities/summer/kayak-inari.webp': 'center 43%',
  '/images/activities/summer/lake-cruise.webp': 'center 41%',
  '/images/activities/summer/reindeer-saytsjarvi.webp': 'center 41%',
  '/images/activities/summer/riisitunturi-tykky.webp': 'center 41%',
  '/images/activities/winter/husky-dogs-ruka.webp': 'center 43%',
  '/images/activities/winter/husky-kennel.webp': 'center 41%',
  '/images/activities/winter/husky-ready-ruka.webp': 'center 43%',
  '/images/activities/winter/husky-ride-ruka.webp': 'center 43%',
  '/images/activities/winter/icebreaker-sampo.webp': 'center 41%',
  '/images/activities/winter/ounasvaara-winter.webp': 'center 39%',
  '/images/activities/winter/reindeer-farm-inari.webp': 'center 41%',
  '/images/activities/winter/reindeer-sleds-inari.webp': 'center 41%',
  '/images/activities/winter/sled-dogs-lapland.webp': 'center 41%',
  '/images/activities/winter/snowmobile-kuntivaara.webp': 'center 41%',
  '/images/activities/winter/snowmobile-river.webp': 'center 41%',
  '/images/activities/winter/snowmobile-saariselka.webp': 'center 43%',
  '/images/activities/winter/snowshoe-forest.webp': 'center 41%',
  '/images/heroes/husky-sled-day.webp': 'center 41%',
  '/images/heroes/slider-08-ruska-hetta-pallas.webp': 'center 39%',
  '/images/hotels/boutique-hotel-rovaniemi.webp': 'center 41%',
  // 20.9.2026 (Vesa: "alasivujen herot leikattu liian mataliksi ja kuvat ei näy kuten pitää"):
  // oletus 'center 35%' näyttää maisemakuvasta taivaan. Näissä aihe on kehyksen keskellä tai
  // alempana, joten ankkuri lasketaan. Mitattu renderöidyltä hero-kaistalta.
  '/images/activities/adventure/korouoma-frozen.webp': 'center 50%',
  '/images/activities/winter/downhill-skiers.webp': 'center 55%',
  // Laskijat ovat kuvan ylapuoliskossa; rajaus pitaa heidat nakyvissa matalassa herossa.
  '/images/activities/winter/skier-powder-carve.webp': 'center 40%',
  // Mokki tayttaa kehyksen; hieman alas, jottei katto leikkaudu matalassa herossa.
  '/images/activities/wellness/wilderness-sauna-morgamoja.webp': 'center 47%',
  '/images/activities/wellness/sauna-interior.webp': 'center 50%',
  '/images/activities/culture/sami-duodji.webp': 'center 50%',
  '/images/activities/summer/lapland-river.webp': 'center 50%',
  '/images/activities/food/lapland-plate.webp': 'center 50%',
  '/images/activities/fishing/fishing-ice.webp': 'center 50%',
  '/images/heroes/rovaniemi-winter-village.webp': '80% 50%',
  '/images/heroes/levi-summer-fell.webp': 'center 45%',
  '/images/activities/summer/kiilopaa-view-east.webp': 'center 55%',
  '/images/activities/culture/snowcastle-kemi.webp': 'center 55%',
  // Subject's head/helmet is near the TOP → anchor higher so it's never cropped.
  '/images/activities/summer/mtb-bikepark.webp': 'center 50%',
  '/images/activities/summer/salmon-fishing.webp': 'center 55%',
  '/images/activities/fishing/fishing-river.webp': 'center 50%',
  '/images/activities/fishing/fishing-ice-dusk.webp': 'center 45%',
  // Wide aurora arcs read best with the sky kept — anchor a touch low.
  '/images/heroes/slider-01-husky-aurora.webp': 'center 53%',
  '/images/heroes/slider-04-glass-igloo.webp': 'center 50%',
  '/images/heroes/slider-07-kayak-lake.webp': 'center 50%',
  '/images/heroes/saariselka-winter.webp': 'center 47%',
  '/images/heroes/inari-winter-lake.webp': 'center 50%',
  '/images/heroes/inari-summer-lake.webp': 'center 50%',
  '/images/heroes/posio-winter-tykky.webp': 'center 50%',
  '/images/heroes/posio-summer-lake.webp': 'center 50%',
  '/images/heroes/pyha-winter-slopes.webp': 'center 50%',
  '/images/heroes/ruka-winter-slopes.webp': 'center 50%',
  '/images/heroes/yllas-winter-road.webp': 'center 50%',
  '/images/heroes/reindeer-winter.webp': 'center 50%',
  '/images/activities/northern-lights/aurora-lake.webp': 'center 47%',
  '/images/activities/northern-lights/aurora-inari-juutuanvuono.webp': 'center 40%',
  '/images/activities/northern-lights/aurora-inari-bands.webp': 'center 45%',
  '/images/activities/northern-lights/aurora-levi-bands.webp': 'center 45%',
  '/images/og/og-default.webp': 'center 45%',
  // Reindeer herd walks along the lower third → keep animals in frame.
  '/images/heroes/reindeer-herd-sunset.webp': 'center 55%',
  '/images/heroes/slider-05-reindeer-lavvu.webp': 'center 53%',
  // Snowmobile rider sits at mid-right; default centre is fine but nudge up.
  '/images/heroes/slider-02-snowmobile-fells.webp': 'center 53%',
  '/images/heroes/snowmobile-safari.webp': 'center 40%',
  // Hikers stand on the ridge in the vertical centre.
  '/images/heroes/slider-03-summer-hike.webp': 'center 50%',
  // Fell resort village sits low → keep it visible.
  '/images/heroes/levi-black-run-view.webp': 'center 50%',
  // Summer lake: paddler + sun are in the lower-mid → anchor low.
  '/images/categories/summer.webp': 'center 50%',
  '/images/heroes/ruka-fell.webp': 'center 50%',
  '/images/heroes/yllas-summer-village.webp': 'center 45%',
  '/images/heroes/rovaniemi-summer-santa.webp': 'center 50%',
  '/images/heroes/tornio-river-dusk.webp': 'center 50%',
  // New destination heroes: pyha fell tops sit mid-high; kemijarvi town+train band
  // is in the UPPER third (frozen lake fills the lower two thirds) → anchor high.
  '/images/heroes/pyha-luosto-fells.webp': 'center 40%',
  '/images/heroes/kemijarvi-lake-town.webp': 'center 30%',
};

// 26.9.2026: nayttotason lisarajaus kohdesivun herolle, kun rajaamattoman CC BY-SA -kuvan
// reunassa on vieraan yrityksen kyltti. Jatkankynttilan panoraamassa (3,17:1) K-Citymarketin
// pylvas on 12,8 % ja Lapland Safarisin kyltti 6,3 % vasemmasta reunasta. Hero on
// tyopoydalla ~3:1 (1920x648 mitattu), joten object-cover nayttaa koko leveyden eika mikaan
// object-position piilota niita. CSS-skaalaus 1,2 oikeasta reunasta jattaa vasemman 17 %
// kehyksen ulkopuolelle kaikilla leveyksilla. Tiedosto on yha koko valokuva: tama on
// nayton rajaus kuten object-fit, ei muokattu teos. Puhelimessa (alle md) ei tarvita: kapea
// kehys nayttaa 80 %:n ankkurilla vain sillan tornin ympariston.
const HERO_FRAME: Record<string, string> = {
  '/images/heroes/rovaniemi-winter-village.webp': 'md:origin-right md:scale-[1.2]',
};

/** Lisaluokat kohdesivun hero-kuvalle (tyhja useimmille). */
export function heroFrameClass(src: string): string {
  return HERO_FRAME[src] ?? '';
}

/** Safe object-position for a hero image so heads/helmets are never cropped. */
export function focalFor(src: string): string {
  return FOCAL[src] ?? 'center 35%';
}
