// All imagery is locally hosted in /public/images/. WebP optimized via
// scripts/optimize-images.mjs. No Google Drive, no Unsplash, no third-party CDN.
//
// CURATED HIGH-RES POOL (12 images, brand-clean, all WebP, generated by Vesa):
//   /heroes/slider-01-husky-aurora.webp        (husky team + aurora)
//   /heroes/slider-02-snowmobile-fells.webp    (snowmobile + fjells)
//   /heroes/slider-03-summer-hike.webp         (summer hike, midnight sun)
//   /heroes/slider-04-glass-igloo.webp         (glass igloo, twilight)
//   /heroes/slider-05-reindeer-lavvu.webp      (reindeer + Sámi lavvu)
//   /categories/summer.webp                    (summer landscape, vertical-friendly)
//   /hotels/glass-igloo-aurora.webp            (single igloo + aurora)
//   /hotels/log-cabin-lakeside.webp            (red log cabin, lakeside)
//   /hotels/fell-resort-levi.webp              (alpine ski resort)
//   /hotels/boutique-hotel-rovaniemi.webp      (modern hotel exterior)
//   /hotels/smoke-sauna-cabin-saariselka.webp  (savusauna cabin)
//   /og/og-default.webp                        (wide aurora composition for OG)

const local = (file: string) => `/images/${file}`;

// === SAFE / CONFIRMED-CLEAN HIGH-RES POOL ===
// Every alias used by data/categories.ts and data/destinations.ts maps to a
// UNIQUE entry in this pool — guarantees no two surfaces share the same image
// at the same time.

export const HERO = {
  // Primary aurora — used in newsletter popup decoration etc.
  aurora:           local('heroes/slider-01-husky-aurora.webp'),

  // Used by destinations.ts / categories.ts via legacy alias names
  auroraLake:       local('og/og-default.webp'),                    // wide aurora
  snowyForest:      local('heroes/slider-02-snowmobile-fells.webp'), // wide forest+sled
  huskyAurora:      local('heroes/slider-01-husky-aurora.webp'),
  huskySnowmobile:  local('heroes/slider-02-snowmobile-fells.webp'),
  campfire:         local('hotels/log-cabin-lakeside.webp'),         // cabin + outdoor
  glassIgloo:       local('hotels/glass-igloo-aurora.webp'),

  // Legacy alias names (used by destinations.ts) — all now map to high-res WebPs
  santaClaus:       local('heroes/slider-05-reindeer-lavvu.webp'),
  reindeerHerd:     local('heroes/slider-05-reindeer-lavvu.webp'),
  huskyTeam:        local('heroes/slider-01-husky-aurora.webp'),
  kidsSnow:         local('og/og-default.webp'),
  cabin:            local('hotels/log-cabin-lakeside.webp'),
  iceLake:          local('og/og-default.webp'),
  fells:            local('hotels/fell-resort-levi.webp'),
  midnightSun:      local('heroes/slider-03-summer-hike.webp'),
  smokesauna:       local('hotels/smoke-sauna-cabin-saariselka.webp'),
  fjell:            local('heroes/slider-02-snowmobile-fells.webp'),
  village:          local('hotels/boutique-hotel-rovaniemi.webp'),
} as const;

// HERO_BRANDED — kept as alias for legacy data references
export const HERO_BRANDED = {
  magicOfLapland:  HERO.glassIgloo,
  gatewayLapland:  HERO.village,
  discoverLapland: HERO.huskySnowmobile,
  tasteArctic:     HERO.smokesauna,
  distinctive:     HERO.huskyAurora,
  homeArctic:      HERO.cabin,
  relaxRecharge:   HERO.smokesauna,
} as const;

// MKT pool — used by categories.ts. Each key maps to a UNIQUE high-res file.
export const MKT = {
  huskyAuroraFamily: HERO.huskyAurora,            // slider-01
  huskySnowmobile:   HERO.huskySnowmobile,        // slider-02
  huskyAurora:       HERO.huskyAurora,            // slider-01
  huskyDaylight:     HERO.huskySnowmobile,        // slider-02
  campfireNight:     HERO.cabin,                  // log-cabin-lakeside
  campfireClose:     HERO.cabin,
  campfireTripod:    HERO.cabin,
  campfireStars:     HERO.cabin,
  igluCouple:        HERO.glassIgloo,             // hotels/glass-igloo-aurora
  igluAurora:        HERO.glassIgloo,
  igluClose:         HERO.glassIgloo,
  igluDramatic:      HERO.glassIgloo,
  reindeerSled:      HERO.santaClaus,             // slider-05-reindeer-lavvu
  iceFishing:        HERO.auroraLake,             // og/og-default
  saunaWinter:       HERO.smokesauna,             // hotels/smoke-sauna-cabin
} as const;

// === Activity → image matcher ===
//
// Match the activity by keyword in title + category and return a relevant
// image. If no keyword matches, fall back to the per-category image (which
// is itself a unique, brand-clean WebP). Never use random hashing — that's
// what produced "snowmobile expedition" cards showing a glass igloo.
//
// When Vesa generates per-activity-type images in a Tier 2 batch, the map
// below grows.

// Order is significant — first match wins, so SPECIFIC keywords come before
// GENERIC ones. e.g. "Polar Bears" must match `bear` before `trail` (which
// might appear in the description) sweeps it to summer-hike.
const KEYWORD_IMAGE: Array<{ match: RegExp; img: string }> = [
  // Specific named places / cultural items first — Tier 2 imagery where available
  { match: /santa(park)?|christmas|joulu|elf|arctic circle (cross|line|marker)/i,
                                                                        img: local('activities/culture/santa-village.webp') },
  { match: /amethyst|gold pan(ning)?|lampivaara|mine\b/i,               img: local('activities/culture/amethyst-mine.webp') },
  { match: /museum|m[uu]seo|s[íi]ida|arktikum|pentik/i,                 img: local('hotels/boutique-hotel-rovaniemi.webp') },
  { match: /polar bear|ranua/i,                                         img: local('activities/wildlife/polar-bears.webp') },
  { match: /bear|wildlife|wolverine|lynx|fox/i,                         img: local('activities/wildlife/polar-bears.webp') },
  { match: /reindeer|s[áa]mi|lavvu|kota dinner/i,                       img: local('heroes/slider-05-reindeer-lavvu.webp') },
  { match: /husky|husk[iy]|sled dog|kennel/i,                           img: local('heroes/slider-01-husky-aurora.webp') },

  // Sports / activities — BEFORE lodging because activity titles are the strongest
  // signal (a "snowmobile expedition" must match snowmobile even if the description
  // mentions "cabin lunch")
  { match: /snowmobile|kelkka|skidoo/i,                                 img: local('heroes/slider-02-snowmobile-fells.webp') },
  { match: /ski(ing)?|slope|piste|biathlon|cross[- ]country|snowboard/i, img: local('hotels/fell-resort-levi.webp') },
  { match: /ice climb|frozen waterfall|korouoma/i,                      img: local('activities/adventure/ice-climbing.webp') },
  { match: /kayak|canoe|paddle|sup\b|raft|river run/i,                  img: local('heroes/slider-03-summer-hike.webp') },
  { match: /boat|cruise|icebreaker|sampo|lake.*tour/i,                  img: local('og/og-default.webp') },
  { match: /salmon|fly[- ]?fish|tornionjoki|teno river/i,               img: local('activities/summer/salmon-fishing.webp') },
  { match: /whitefish|ice fish/i,                                       img: local('hotels/log-cabin-lakeside.webp') },
  { match: /fish(ing)?/i,                                               img: local('hotels/log-cabin-lakeside.webp') },
  { match: /mountain bike|mtb|fat bike|cycling|bike park/i,             img: local('heroes/slider-03-summer-hike.webp') },
  { match: /golf/i,                                                     img: local('heroes/slider-03-summer-hike.webp') },
  { match: /berry|cloudberry|forag|mushroom/i,                          img: local('heroes/slider-03-summer-hike.webp') },
  { match: /campfire|kota cook|outdoor (cooking|dinner)/i,              img: local('hotels/log-cabin-lakeside.webp') },

  // Lodging / structures (after sports)
  { match: /glass igloo|aurora cabin|igloo/i,                           img: local('hotels/glass-igloo-aurora.webp') },
  { match: /smoke sauna|savusauna|kiilop[ää]+/i,                        img: local('hotels/smoke-sauna-cabin-saariselka.webp') },
  { match: /ice (hotel|chapel|castle|restaurant|gallery)|snowcastle|snow ?hotel|ice village/i,
                                                                        img: local('hotels/glass-igloo-aurora.webp') },
  { match: /ice floating|float experience|arctic float/i,               img: local('activities/wellness/ice-floating.webp') },
  { match: /hot tub|wood[- ]fired tub|jacuzzi/i,                        img: local('activities/wellness/spa-hottub.webp') },
  { match: /spa|wellness|massage/i,                                     img: local('activities/wellness/spa-hottub.webp') },
  { match: /float/i,                                                    img: local('activities/wellness/ice-floating.webp') },
  { match: /sauna/i,                                                    img: local('hotels/smoke-sauna-cabin-saariselka.webp') },
  { match: /cabin|log house|lakeside lodge/i,                           img: local('hotels/log-cabin-lakeside.webp') },

  // Generic outdoor
  { match: /hike|hiking|trail|trek|fjell hike|fell hike|karhunkierros/i, img: local('heroes/slider-03-summer-hike.webp') },
  { match: /aurora|northern light|revontul/i,                            img: local('og/og-default.webp') },
  { match: /midnight sun|summer/i,                                       img: local('categories/summer.webp') },

  // City/destination tour catch-alls
  { match: /city tour|rovaniemi tour|kemi tour|tornio tour/i,           img: local('hotels/boutique-hotel-rovaniemi.webp') },
];

export interface ActivityImageInput {
  title?: string;
  category?: string;
  categorySlug?: string;
  description?: string;
}

export function imageForActivity(act: ActivityImageInput | string): string {
  // Backwards-compat: legacy callers passed the id string. Best-effort
  // fallback to category cabin image when only a string is given.
  if (typeof act === 'string') {
    return imageForCategory('adventure');
  }
  const haystack = `${act.title || ''} | ${act.category || ''} | ${act.description || ''}`;
  for (const { match, img } of KEYWORD_IMAGE) {
    if (match.test(haystack)) return img;
  }
  return imageForCategory(act.categorySlug || 'adventure');
}

// Per-category curated hero — UNIQUE per category. No duplicates.
const CATEGORY_HERO: Record<string, string> = {
  adventure:        local('heroes/slider-02-snowmobile-fells.webp'),
  animals:          local('heroes/slider-01-husky-aurora.webp'),
  'northern-lights': local('og/og-default.webp'),
  'winter-sports':  local('hotels/fell-resort-levi.webp'),
  wellness:         local('hotels/smoke-sauna-cabin-saariselka.webp'),
  culture:          local('heroes/slider-05-reindeer-lavvu.webp'),
  summer:           local('categories/summer.webp'),
  food:             local('hotels/log-cabin-lakeside.webp'),
};

export function imageForCategory(slug: string): string {
  return CATEGORY_HERO[slug] ?? HERO.huskyAurora;
}

// Per-destination curated hero — UNIQUE per destination.
const DEST_HERO: Record<string, string> = {
  rovaniemi:  local('heroes/slider-05-reindeer-lavvu.webp'),
  levi:       local('hotels/fell-resort-levi.webp'),
  yllas:      local('heroes/slider-02-snowmobile-fells.webp'),
  saariselka: local('hotels/smoke-sauna-cabin-saariselka.webp'),
  inari:      local('og/og-default.webp'),
  ruka:       local('heroes/slider-03-summer-hike.webp'),
  posio:      local('hotels/log-cabin-lakeside.webp'),
  tornio:     local('hotels/boutique-hotel-rovaniemi.webp'),
};

export function imageForDestination(slug: string): string {
  return DEST_HERO[slug] ?? HERO.huskyAurora;
}
